# Generated by Django 4.1.7 on 2023-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_cliente_id_alter_detallefactura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Unidad'), ('2', 'Litro'), ('3', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
